; PlatformIO Project Configuration File

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
monitor_filters = esp32_exception_decoder ; Помогает расшифровывать ошибки (Guru Meditation Error), если они возникнут

; ВНИМАНИЕ: Сюда нужно вписать библиотеки, которые уже используются в проекте v1.0.1
; lib_deps = 
;     ... (например, IBusBM, ESP32-audioI2S и т.д.)

; ВНИМАНИЕ: Если для аудиофайлов v1.0.1 использовалась своя таблица разделов (partitions.csv), раскомментируйте:
; board_build.partitions = huge_app.csv 

; -----------------------------------------
; Конфигурация для танка T3 (LOLIN32 Lite)
; -----------------------------------------
[env:t3_lolin32_lite]
board = lolin32_lite
build_flags = 
    -D TANK_BOARD_LOLIN
    -D TANK_MODEL_T3

; -----------------------------------------
; Конфигурация для танка T4 (DEVKIT V1)
; -----------------------------------------
[env:t4_devkit_v1]
board = esp32doit-devkit-v1
build_flags = 
    -D TANK_BOARD_DEVKIT
    -D TANK_MODEL_T4