; PlatformIO Project Configuration File

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

; -----------------------------------------
; Конфигурация для танка на LOLIN32 Lite
; -----------------------------------------
[env:lolin32_lite]
board = lolin32_lite
build_flags = 
    -D TANK_BOARD_LOLIN   ; <--- Создаем макрос для Lolin
    -D TANK_MODEL_P3  ; 

; -----------------------------------------
; Конфигурация для танка на DEVKIT V1
; -----------------------------------------
[env:devkit_v1]
board = esp32doit-devkit-v1
build_flags = 
    -D TANK_BOARD_DEVKIT  ; <--- Создаем макрос для DevKit
    -D TANK_MODEL_P4 ; (Опционально)